name: ci
on:
  pull_request:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v12
        with:
          name: bernardo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: check
        run: nix flake check -L
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v12
        with:
          name: bernardo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: nix build
        id: build
        run: echo "::set-output name=result::$(nix build -L --print-out-paths)"
      - name: cachix-push
        if: github.ref == 'refs/heads/master'
        run: cachix push bernardo "${{ steps.build.outputs.result }}"
      - name: upload-artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: cv
          path: ${{ steps.build.outputs.result }}/cv.pdf
          if-no-files-found: error
          retention-days: 1
