name: CI
on:
  push:
    branches:
      - master
      - flake-update
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
          extra_nix_config: "experimental-features = nix-command flakes"
      - uses: cachix/cachix-action@v8
        with:
          name: bernardo
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: chktex
        run: nix develop -c chktex cv.tex
      - name: latexindent
        run: |
          nix develop -c latexindent cv.tex > cv.tex.fmt
          cmp --silent cv.tex cv.tex.fmt || exit 1

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
          extra_nix_config: "experimental-features = nix-command flakes"
      - uses: cachix/cachix-action@v8
        with:
          name: bernardo
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: nix-build
        run: nix build -L

  publish:
    runs-on: ubuntu-latest
    needs: [ lint, build ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
          extra_nix_config: "experimental-features = nix-command flakes"
      - uses: cachix/cachix-action@v8
        with:
          name: bernardo
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: nix-build
        run: |
          nix build -L
          mkdir -p ~/
          cp ./result/cv.pdf ~/
      - uses: mathieudutour/github-tag-action@v5.4
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.tag.outputs.changelog }}
          tag_name: ${{ steps.tag.outputs.new_tag }}
          files: ~/cv.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
