name: CI
on:
  push:
    branches:
      - master
      - flake-update
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
          extra_nix_config: "experimental-features = nix-command flakes"
      - uses: cachix/cachix-action@v8
        with:
          name: bernardo
          signingKey: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: lints
        run: |
          nix develop -c echo "fixme"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
          extra_nix_config: "experimental-features = nix-command flakes"
      - uses: cachix/cachix-action@v8
        with:
          name: bernardo
          signingKey: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: nix-build
        run: nix build -L
      - uses: actions/upload-artifact@v2
        with:
          name: cv
          path: result/cv.pdf
