name: ci
on:
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: bernardo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: chktex
        run: nix develop -c chktex cv.tex
      - name: latexindent
        run: |
          nix develop -c latexindent cv.tex > cv.tex.fmt
          cmp --silent cv.tex cv.tex.fmt || exit 1
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: bernardo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: nix-build
        run: nix build -L
      - name: upload-artifact
        if: github.event_name == 'workflow_call'
        uses: actions/upload-artifact@v3
        with:
          name: cv
          path: ./result/cv.pdf
          if-no-files-found: error
          retention-days: 1
