name: ci
on:
  pull_request:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: bernardo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: check
        run: nix flake check -L
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: bernardo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: nix-build
        run: nix build -L
      - name: cachix-push
        if: github.event_name == 'workflow_call'
        run: cachix push bernardo ./result
      - name: upload-artifact
        if: github.event_name == 'workflow_call'
        uses: actions/upload-artifact@v3
        with:
          name: cv
          path: ./result/cv.pdf
          if-no-files-found: error
          retention-days: 1
