name: ci
on:
  pull_request:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

env:
  flake: github:${{ github.repository }}/${{ github.sha }}
  nix-conf: |-
    accept-flake-config = true
    builders-use-substitutes = true
    max-jobs = auto

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: ${{ env.nix-conf }}
      - uses: cachix/cachix-action@v13
        with:
          name: bernardo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: nix-flake-check
        run: nix flake check '${{ env.flake }}'
  flake-show:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: ${{ env.nix-conf }}
      - uses: cachix/cachix-action@v13
        with:
          name: bernardo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: nix-flake-show
        run: nix flake show '${{ env.flake }}'
  flake-build:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: ${{ env.nix-conf }}
      - uses: cachix/cachix-action@v13
        with:
          name: bernardo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: nix-build
        id: build
        run: |
          nix build -L '${{ env.flake }}'
          echo "result=$(realpath ./result)" >> "$GITHUB_OUTPUT"
      - name: upload-artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: ${{ steps.build.outputs.result }}/cv.pdf
          if-no-files-found: error
          retention-days: 1
